name: second Work Flow

on: push

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print node version
        run: node -v
      - run: echo "${{toJson(env)}}"
      - run: echo ${{vars.COSTUME_VERIABLES}}
      - run: echo ${{secrets.AWS_SECREET}}

  development-job:
    runs-on: ubuntu-latest
    environment: DEVELOPMENT
    steps:
      - name: Print veriables
        run: echo ${{vars.ENV}}

  production-jon:
    runs-on: ubuntu-latest
    environment: PRODUCTION
    steps:
      - name: Print Veriables
        run: echo ${{vars.ENV}}

  print-push-branch:
    runs-on: ubuntu-latest
    steps:
      - name: print push branch
        run: echo ${{github.action_ref}}
