name: second Work Flow

on: push

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print node version
        run: node -v
      - run: echo "${{toJson(env)}}"
      - run: echo ${{vars.COSTUME_VERIABLES}}
      - run: echo ${{secrets.AWS_SECREET}}
