name: my first workflow
on: [push, workflow_dispatch]
jobs:
  first-job:
    env:
      other: "this is the env value"
    runs-on: ubuntu-latest
    steps:
      - name: List all files
        run: ls -a
      - name: print working directory
        run: pwd
      - name: print node version
        run: node -v
      - run: echo ${{env.other}}
